### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by BlackIQ** [amirshnll/amirshnll#1]
سلام. خوبید سلامتید؟

ببینید، گیتهاب کارت بیشترین زبان استفاده شده به این صورت هستند که مثلا میشه شما زبان اچ تی ام ال رو هاید کنید، یا سی اس اس رو هاید کنید.

فقط کافیه که ته لینک یه گت جدید اضافه کنید. مثل این:

`&hide=html`

یا برای بیشتر از یکی:

`&hide=html,css,sass`

خواستم فورک کنم پول رکوئست بزنم، گفتم اول به خودتون اعلام کنم. اگه مورد نداشته باشه، بفرمایید چه زبان هایی هاید بشه و انجام بدم. البته خودتون هم میتونید انجام بدید.

ممنون مرسی.

امیر.

**Comment by amirshnll** [comment]
مرسی خودم اصلاح کردم تشکر بابت اطلاع دادنت خیلی بدردم خورد
